import { describe, expect, it } from "vitest";
import findingTypes from "@/lib/generated/reference/finding-types.json";

// The queue's labels come from the finding-type registry, generated by
// `scripts/gen/docs_reference.py --write`; these pin what a reader sees.
describe("finding type labels", () => {
  const byType = Object.fromEntries(findingTypes.types.map((t) => [t.type, t]));

  it("labels every type with a title and a meaning", () => {
    for (const t of findingTypes.types) {
      expect(t.title, t.type).toBeTruthy();
      expect(t.description, t.type).toBeTruthy();
    }
  });

  it("keeps the labels the queue has always shown", () => {
    expect(byType.guardrail_detection.title).toBe("Guardrail catch");
    expect(byType.shadow_agent.title).toBe("Unregistered agent");
    expect(byType.redteam_over_block.title).toBe("Over-blocking");
  });

  it("says budget_breach is a detector over its latency budget, not spend", () => {
    expect(byType.budget_breach.title).toBe("Detector over budget");
    expect(byType.budget_exhausted.title).toBe("Budget exhausted");
  });
});
