"""The coverage page's data cannot drift from the taxonomy it claims to show.

`dashboard/lib/coverage.json` is generated by `scripts/probe/run.py --json` and
rendered by `/coverage`. A committed artefact is a copy, and a copy rots: add a
scenario to the taxonomy, forget to regenerate, and the site keeps publishing
the old total with the same confident wording.

Deliberately split from the nightly rather than duplicating it. This asserts
the *shape* — every scenario present, every verdict matching, the headline
figures consistent — which is fast and catches the drift that actually
happens. Whether each probe still passes against the running product is the
nightly harness's job and takes minutes, not milliseconds.

`benchmarks/claims.yaml` exists because two published figures were corrected by
hand in a single week. This is the same guard for a different artefact.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
COVERAGE_JSON = REPO_ROOT / "dashboard" / "lib" / "coverage.json"

sys.path.insert(0, str(REPO_ROOT))


@pytest.fixture(scope="module")
def published() -> dict:
    return json.loads(COVERAGE_JSON.read_text())


@pytest.fixture(scope="module")
def taxonomy():
    from scripts.probe.taxonomy import SCENARIOS

    return SCENARIOS


def test_the_file_exists_and_names_its_generator(published):
    assert published["generated_by"] == "scripts/probe/run.py --json"


def test_every_scenario_is_published(published, taxonomy):
    assert {row["id"] for row in published["rows"]} == {s.id for s in taxonomy}
    assert published["scenarios"] == len(taxonomy)


def test_no_verdict_has_been_upgraded_in_the_copy(published, taxonomy):
    """The failure that would matter: the page claiming a control the
    taxonomy does not."""
    expected = {s.id: s.expect for s in taxonomy}
    for row in published["rows"]:
        assert row["verdict"] == expected[row["id"]], row["id"]


def test_the_headline_numbers_follow_from_the_rows(published):
    """A hand-edited total is the oldest way a coverage page overstates."""
    order = {"covered": 1.0, "partial": 0.5, "absent": 0.0, "by design": 0.0}
    rows = published["rows"]
    scored = sum(order[r["verdict"]] for r in rows)
    assert published["weighted_coverage"] == pytest.approx(scored / len(rows), abs=0.0001)
    assert published["executable"] == sum(1 for r in rows if r["executable"])
    assert published["verified"] == sum(1 for r in rows if r["verified"])


def test_verified_is_never_claimed_for_a_row_that_cannot_run(published):
    """The distinction the whole page is built on. A row assessed by reading
    the code must not borrow the credibility of one that was executed."""
    for row in published["rows"]:
        if not row["executable"]:
            assert row["verified"] is False, row["id"]


def test_the_layer_totals_match_the_rows(published):
    from collections import Counter

    counted = Counter(row["layer"] for row in published["rows"])
    for layer in published["layers"]:
        assert layer["total"] == counted[layer["layer"]], layer["layer"]


def test_the_gaps_are_published_not_quietly_dropped(published):
    """A coverage page that only listed successes would be evidence of
    nothing. The page renders `absent` rows by name, so there has to be a
    row shape it can render."""
    absent = [r for r in published["rows"] if r["verdict"] == "absent"]
    for row in absent:
        assert row["name"] and row["layer"], row["id"]
