import type { Metadata } from "next";
import Link from "next/link";

import { Code, NextSteps, Output } from "@/components/docs/blocks";
import { publicPageMetadata } from "@/lib/site";

export const metadata: Metadata = publicPageMetadata({
  title: "Limits",
  description: "What AgentFox does not do, what is only partly built, and what is only as good as your declarations.",
  path: "/docs/limits",
});

const PARTIAL: [string, string][] = [
  ["Registry and discovery", "No connector-based estate discovery. Agents are found by scanning code, by their traffic, and by registration."],
  ["Identity", "No live identity provider. No Entra or Okta integration; principals and grants live in AgentFox."],
  ["Authentication", "Operator tokens and the development-mode gate ship. OIDC and SCIM do not."],
  ["Action assurance", "Cascade analysis is only as good as the trigger declarations it is given: an undeclared webhook stays invisible. Shell analysis is a deny-list, not a parser."],
  ["Entitlement", "The OpenFGA adapter is a declared seam, not an implementation."],
  ["Source provenance", "No catalog ingestion (DataHub, OpenMetadata, Unity). You declare sources yourself."],
  ["Context integrity", "Ingestion and retrieval gates report problems. Semantic chunk repair and automatic re-extraction of a corrupt document are not built; dropping the document is the operator's decision."],
  ["Evaluation", "No annotation queue for human review of borderline eval results."],
  ["Failure attribution", "Attributes a failure only against constraints that were written down. An expectation nobody typed is invisible."],
  ["Compliance", "No dynamic risk scoring and no workflow engine."],
  ["Loop governance", "Catches identical repeats, alternating cycles and steps with no new observation. An agent that is wrong but varied still looks like an agent working."],
  ["Async work", "Jobs run in process with retries and a dead letter. No Redis or SQS backend."],
  ["Persistence at scale", "Pooling ships, and SQLite is refused for multi-worker servers. Scale-out under load is untested."],
  ["Fail-open budgets", "Budgets and rate limits are per process, so N workers get N times the declared budget."],
  ["Tool contracts", "Data-access scoping is only as good as the table declarations; an undeclared table is reported, never assumed safe. Register checks are lexical."],
  ["Business rules", "Policy compiled from prose is deterministic; prose with no parseable structure is reported as inexpressible rather than guessed. No model-assisted path."],
];

export default function Page() {
  return (
    <article className="docs-doc">
      <p className="docs-kicker">Operate</p>
      <h1>Limits</h1>
      <p className="docs-lede">
        What AgentFox does not do, what is only partly built, and what depends entirely on
        what you declare. Written down so you do not discover it later.
      </p>

      <h2>When to use this</h2>
      <p>
        Before you rely on a control, and before you tell someone else what AgentFox covers.
        The per-capability status below comes from <code>docs/status.md</code> in the
        repository, which is generated by probing the code rather than written by hand.
        Detection&apos;s measured misses are on <Link href="/docs/benchmarks">Benchmarks</Link>.
      </p>

      <h2>It is only as good as your declarations</h2>
      <ul>
        <li>
          <b>Impact is a floor.</b> A destructive tool declared <code>read</code> is treated as
          read by everything downstream. A shell is one tool for both <code>ls</code> and{" "}
          <code>rm -rf</code>. Tools that <code>agentfox.auto()</code> registers get an impact
          guessed from their name, marked <code>inferred</code> until you confirm it with{" "}
          <code>agentfox declare tool</code>.
        </li>
        <li>
          <b>Output trust is a claim you make.</b> Declaring a tool&apos;s output{" "}
          <code>trusted</code> stops values copied out of it counting as untrusted. Declare it
          for a system of record you control, never for anything a stranger can write.
        </li>
        <li>
          <b>The scan reads names.</b> <code>agentfox scan</code> classifies tools from names
          and descriptions. It can flag a harmless tool and miss one named{" "}
          <code>do_thing</code>; an unrecognised MCP server is reported as unknown, never as
          safe.
        </li>
        <li>
          <b>You declare the estate yourself.</b> Principals, grants, source tiers and
          row-scoped tables live in AgentFox. The seams for Okta, DataHub and OpenFGA exist;
          the integrations do not.
        </li>
      </ul>
      <p>
        <code>agentfox doctor</code> grades the declarations you have, and{" "}
        <code>agentfox declare list tools</code> shows which impacts are still guesses:
      </p>
      <Code>{`agentfox declare list tools`}</Code>
      <Output>{`  tool             impact                                                    output       triggers
  crm_lookup       read (inferred — confirm with \`agentfox declare tool\`)    untrusted    —
…`}</Output>

      <h2>Containment costs legitimate work</h2>
      <p>
        Under the default session-level provenance, once an agent has read untrusted
        content, every later irreversible call needs a person. On AgentDojo only 24 of 97
        benign tasks ran without an escalation. Per-argument provenance lets more through and
        misses attacks whose values do not appear in an argument. Neither is free; see{" "}
        <Link href="/docs/benchmarks#utility">the utility table</Link>.
      </p>

      <h2>What each integration does not see</h2>
      <ul>
        <li>
          <b><code>agentfox.auto()</code></b>: not the OpenAI Responses API, and not a tool your
          code calls without the model asking for it.
        </li>
        <li>
          <b>The gateway</b>: only what your code sends to it.
        </li>
        <li>
          <b>Coding-agent hooks</b>: only the agent on the machine they are installed on. A
          session running in the vendor&apos;s cloud is invisible to them, and{" "}
          <code>PostToolUse</code> cannot withdraw a call that already ran.
        </li>
        <li>
          <b>Detectors</b>: text only. No images, audio or files.
        </li>
      </ul>

      <h2>Compliance mappings are drafts</h2>
      <p>
        The 43 controls are mapped to the EU AI Act, ISO 42001, NIST AI RMF, SOC 2, OWASP LLM,
        OWASP Agentic and MITRE ATLAS by engineers, from the framework texts. Counsel has not
        reviewed them. Evidence packages include them labelled{" "}
        <code>DRAFT — UNVERIFIED / NOT LEGAL ADVICE</code>. Control status is computed from
        what agents did; it is not a certification. See{" "}
        <Link href="/docs/guides/audit-evidence">Prove it to an auditor</Link>.
      </p>

      <h2>Version 0.3</h2>
      <ul>
        <li>No SSO, OIDC or SCIM. The first operator comes from GitHub sign-in or <code>agentfox admin seed</code>.</li>
        <li>One organisation per deployment, enforced at the database session.</li>
        <li>Text only.</li>
      </ul>

      <h2>Partly built</h2>
      <p>
        Each of these works, with a specific piece missing. From the generated status table
        (25 of 41 tracked capabilities built, 16 partial, none absent):
      </p>
      <table>
        <thead>
          <tr>
            <th>Area</th>
            <th>What is missing</th>
          </tr>
        </thead>
        <tbody>
          {PARTIAL.map(([area, gap]) => (
            <tr key={area}>
              <td>{area}</td>
              <td>{gap}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2>Detection</h2>
      <p>
        Detectors raise an attacker&apos;s cost; they are not a defence on their own. An
        adaptive attacker that reads the verdict and retries gets 73% of the attacks the
        default detectors catch through within 50 attempts. The model-backed detectors are
        opt-in, need weights, and can time out on long inputs; with <code>fail_mode</code>{" "}
        left at <code>open</code>, a timeout lets the request through and records the gap.{" "}
        <code>agentfox doctor</code> says so on every run.
      </p>

      <NextSteps
        items={[
          { href: "/docs/benchmarks", label: "Benchmarks", why: "the measured misses and costs" },
          { href: "/docs/concepts", label: "Concepts", why: "what each control actually checks" },
          { href: "/docs/support", label: "Support", why: "report something that should work and does not" },
        ]}
      />
    </article>
  );
}
