"""Open Policy Agent adapter.

OPA is the policy decision engine: CNCF-graduated, battle-tested,
sub-millisecond, and — the part that matters commercially — a language enterprise
platform teams already run and already trust in their admission controllers.

Our declarative policy compiles *to* Rego rather than replacing it, so a customer
who wants to write Rego directly can, and a customer whose auditor wants to read
policy in plain YAML can too. Cedar (also Apache-2.0, formally verified) is a
drop-in second option behind the same protocol.

Exposure if OPA changes status: **low.** The native engine is the default and the
two are cross-verified in the test suite.
"""

from __future__ import annotations

import json
import logging

import httpx

from agentfox.core.config import get_settings
from agentfox.platform.policy.model import FiredRule, PolicyDecision, PolicyDocument, PolicyInput

log = logging.getLogger(__name__)


def compile_to_rego(policy: PolicyDocument, *, version: int | None = None) -> str:
    """Compile a declarative policy to a Rego module.

    Emits one ``fired`` rule per policy rule plus a verdict aggregation, which keeps
    the generated module readable — a compiled artefact nobody can read is a
    compliance liability, not an implementation detail.

    ``version`` is the stored version being compiled. The document's own ``version``
    is whatever the YAML said when it was first written; the store numbers versions
    itself, so a header citing the YAML's number named a version that is not the one
    in force.
    """
    stamp = f"v{version}" if version is not None else f"v{policy.version} (unsaved)"
    lines = [
        f"# Generated by AgentFox from policy '{policy.key}' {stamp}.",
        "# Do not edit — regenerate from the declarative source.",
        f"package agentfox.policy.{policy.key.replace('-', '_')}",
        "",
        "import rego.v1",
        "",
        f'default verdict := "{policy.default_effect}"',
        "",
    ]

    rank = {
        "allow": 0,
        "tokenize": 1,
        "mask": 2,
        "redact": 3,
        "abstain": 4,
        "escalate": 5,
        "block": 6,
    }
    for rule in policy.rules:
        if not rule.enabled:
            continue
        conds = _rego_conditions(rule)
        body = "\n".join(f"    {c}" for c in conds) if conds else "    true"
        lines += [
            f"# {rule.description or rule.id}",
            "fired contains out if {",
            body,
            "    out := {",
            f'        "rule_id": "{rule.id}",',
            f'        "effect": "{rule.effect}",',
            f'        "reason": {json.dumps(rule.reason or rule.id)},',
            f'        "severity": "{rule.severity}",',
            f'        "controls": {json.dumps(rule.controls)},',
            "    }",
            "}",
            "",
        ]

    lines += [
        "effect_rank := " + json.dumps(rank),
        "",
        "verdict := v if {",
        "    count(fired) > 0",
        "    ranks := [effect_rank[f.effect] | some f in fired]",
        "    top := max(ranks)",
        "    some f in fired",
        "    effect_rank[f.effect] == top",
        "    v := f.effect",
        "}",
        "",
        'decision := {"verdict": verdict, "rules_fired": fired}',
        "",
    ]
    return "\n".join(lines)


def _rego_conditions(rule) -> list[str]:
    c = rule.when
    out: list[str] = []
    if c.surface:
        out.append(f"input.surface in {json.dumps(c.surface)}")
    if c.environment:
        out.append(f"input.environment in {json.dumps(c.environment)}")
    if c.agent:
        out.append(f"glob.match({json.dumps(c.agent)}, [], input.agent)")
    if c.risk_tier:
        out.append(f"input.risk_tier in {json.dumps(c.risk_tier)}")
    if c.tool:
        out.append(f"glob.match({json.dumps(c.tool)}, [], input.tool)")
    if c.tool_impact:
        out.append(f"input.tool_impact in {json.dumps(c.tool_impact)}")
    if c.detection:
        d = c.detection
        pred = [f"det.score >= {d.min_score}"]
        if d.entity:
            pred.append(f"det.entity_type == {json.dumps(d.entity)}")
        if d.entity_prefix:
            pred.append(f"startswith(det.entity_type, {json.dumps(d.entity_prefix)})")
        out.append(
            "count([det | some det in input.detections; " + "; ".join(pred) + f"]) >= {d.min_count}"
        )
    if c.argument:
        path = ".".join(p for p in c.argument.path.replace("[", ".").replace("]", "").split("."))
        op = {
            "eq": "==",
            "ne": "!=",
            "gt": ">",
            "gte": ">=",
            "lt": "<",
            "lte": "<=",
        }.get(c.argument.op)
        if op:
            out.append(f"input.arguments.{path} {op} {json.dumps(c.argument.value)}")
        elif c.argument.op == "in":
            out.append(f"input.arguments.{path} in {json.dumps(c.argument.value)}")
        elif c.argument.op == "contains":
            out.append(f"contains(input.arguments.{path}, {json.dumps(c.argument.value)})")
        elif c.argument.op == "matches":
            out.append(f"regex.match({json.dumps(c.argument.value)}, input.arguments.{path})")
    if c.taint_exceeds:
        from agentfox.core.vocab import TAINT_ORDER

        worse = [
            s for s in TAINT_ORDER if TAINT_ORDER.index(s) > TAINT_ORDER.index(c.taint_exceeds)
        ]
        out.append(f"input.taint.max_source in {json.dumps(worse)}")
    if c.capability:
        out.append(f'input.capability.state == "{c.capability}"')
    if c.budget_exceeded is not None:
        out.append(f"input.budget.exceeded == {str(c.budget_exceeded).lower()}")
    if c.loop_detected is not None:
        out.append(f"input.budget.loop_detected == {str(c.loop_detected).lower()}")
    if c.detector_degraded is not None:
        out.append(f"input.detector_degraded == {str(c.detector_degraded).lower()}")
    return out


class OpaPolicyEngine:
    """Calls a running OPA sidecar. Falls back to the native engine if unreachable."""

    name = "opa"

    def __init__(self, url: str | None = None, timeout_ms: int = 30) -> None:
        self.url = (url or get_settings().opa_url).rstrip("/")
        self.timeout_s = timeout_ms / 1000

    def available(self) -> bool:
        try:
            r = httpx.get(f"{self.url}/health", timeout=self.timeout_s)
            return r.status_code == 200
        except Exception:
            return False

    def put_policy(self, policy: PolicyDocument) -> None:
        module = policy.key.replace("-", "_")
        httpx.put(
            f"{self.url}/v1/policies/agentfox_{module}",
            content=compile_to_rego(policy),
            headers={"Content-Type": "text/plain"},
            timeout=5.0,
        ).raise_for_status()

    def evaluate(self, policy: PolicyDocument, pinput: PolicyInput) -> PolicyDecision:
        module = policy.key.replace("-", "_")
        payload = {"input": self._shape(pinput)}
        try:
            r = httpx.post(
                f"{self.url}/v1/data/agentfox/policy/{module}/decision",
                json=payload,
                timeout=self.timeout_s,
            )
            r.raise_for_status()
            result = r.json().get("result") or {}
        except Exception as exc:
            # Never let a policy-engine outage take the customer's agent down.
            log.warning("OPA unavailable (%s); falling back to native engine", exc)
            from agentfox.platform.policy.engine import NativePolicyEngine

            decision = NativePolicyEngine().evaluate(policy, pinput)
            decision.engine = "native(opa-fallback)"
            return decision

        # Every block carries an auditable reason. A rule whose reason is meant
        # to be generated (the capability-constraint rule names the limit and the
        # value that failed it, which cannot be written into the pack) comes back
        # from OPA with an empty string, so generate it here exactly as the native
        # engine does rather than shipping a blank.
        from agentfox.platform.policy.engine import NativePolicyEngine

        by_id = {rule.id: rule for rule in policy.rules}
        fired = []
        for f in result.get("rules_fired", []):
            rule_id = f.get("rule_id", "?")
            reason = f.get("reason", "")
            if not reason and rule_id in by_id:
                reason = NativePolicyEngine._explain(by_id[rule_id], pinput)
            # Static per rule, so read from the rule rather than carried through Rego.
            source = by_id.get(rule_id)
            fired.append(
                FiredRule(
                    rule_id=rule_id,
                    effect=f.get("effect", "block"),
                    reason=reason,
                    severity=f.get("severity", "medium"),
                    controls=list(f.get("controls", [])),
                    mode=policy.mode,
                    message=source.message if source else "",
                    on_block=source.on_block if source else "refuse",
                )
            )
        effective = result.get("verdict", policy.default_effect)
        return PolicyDecision(
            verdict=effective if policy.mode == "enforce" else "allow",
            effective_verdict=effective,
            rules_fired=fired,
            policy_key=policy.key,
            policy_version=policy.version,
            mode=policy.mode,
            engine=self.name,
        )

    @staticmethod
    def _shape(p: PolicyInput) -> dict:
        data = p.to_json()
        cap = dict(p.capability)
        if not cap.get("granted", True):
            # Same split as NativePolicyEngine._capability_state: a grant that exists
            # and was exceeded is not the absence of a grant.
            cap["state"] = "constraint_violated" if cap.get("constraint_violations") else "denied"
        elif cap.get("requires_approval"):
            cap["state"] = "requires_approval"
        else:
            cap["state"] = "granted"
        data["capability"] = cap
        return data
